export const QUERY_KEY = {
  auth_user: 'auth_user',
  products: 'products',
  SELECTED_T_SHIPPING_RESULT: 'SELECTED_T_SHIPPING_RESULT',
  PRODUCT_ID_PACKAGE_STYLE_BIN_QTY: 'PRODUCT_ID_PACKAGE_STYLE_BIN_QTY',
  CURRENTLY_EDITING_T_STOCK: 'CURRENTLY_EDITING_T_STOCK',
};
